import ITutorial from "src/interfaces/ITutorial";

/**
 * Represents a PARTIAL tutorial, typically data sent
 * to create a tutorial from the client will be cast to this
 *
 * @class
 * @author ale8k
 */
export default abstract class PartialTutorial implements ITutorial {
    /**
     * The tutorial GUID, generated by Mongo
     *  - Is optional, as we may attempt to save a tutorial but it will not have
     *  and ID until retrieved by Mongo
     * @abstract
     * @type {string}
     * @memberof Tutorial
     */
    public abstract _id?: string;
    /**
     * The tutorial name
     * @abstract
     * @type {string}
     * @memberof PartialTutorial
     */
    public abstract name: string;
    /**
     * The tutorial html (parsed from markdown)
     * @abstract
     * @type {string}
     * @memberof PartialTutorial
     */
    public abstract html: string;
    /**
     * The tutorial markdown (raw)
     * @abstract
     * @type {string}
     * @memberof PartialTutorial
     */
    public abstract markdown: string;
    /**
     * The tutorial category
     * @abstract
     * @type {string}
     * @memberof PartialTutorial
     */
    public abstract category: string;
}
