import ITutorial from "src/interfaces/ITutorial";

/**
 * Represents a PARTIAL tutorial, typically data sent
 * to create a tutorial from the client will be cast to this
 *
 * @class
 * @author ale8k
 */
export default class PartialTutorial implements ITutorial {
    /**
     * The tutorial GUID, generated by Mongo
     *  - Is optional, as we may attempt to save a tutorial but it will not have
     *  and ID until retrieved by Mongo
     *
     * @type {string}
     * @memberof PartialTutorial
     */
    public _id?: string;
    /**
     * The tutorial name
     *
     * @type {string}
     * @memberof PartialTutorial
     */
    public name: string;
    /**
     * The tutorial html (parsed from markdown)
     *
     * @type {string}
     * @memberof PartialTutorial
     */
    public html: string;
    /**
     * The tutorial markdown (raw)
     *
     * @type {string}
     * @memberof PartialTutorial
     */
    public markdown: string;
    /**
     * The tutorial category
     *
     * @type {string}
     * @memberof PartialTutorial
     */
    public category: string;
}
